[Application Options]
tlsextradomain=lnd
tlsextradomain=localhost
tlsextraip=127.0.0.1
tlsextraip=172.20.0.20

# Signet data directory
datadir=/root/.lnd/data
tlscertpath=/root/.lnd/tls.cert
tlskeypath=/root/.lnd/tls.key
adminmacaroonpath=/root/.lnd/data/chain/bitcoin/signet/admin.macaroon
readonlymacaroonpath=/root/.lnd/data/chain/bitcoin/signet/readonly.macaroon
invoicemacaroonpath=/root/.lnd/data/chain/bitcoin/signet/invoice.macaroon
